# -*- coding: utf-8 -*-
"""Taller 1 de electiva Robotica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mP6w0d385nM-um_4B38o7kkSnWz49KRS
"""

#1. Realice un programa que sume, reste, multiplique (producto punto y producto cruz) y divida dos
#vectores previamente inicializados.

import numpy as np

# Inicialización de vectores
v1 = np.array([1, 2, 3])
v2 = np.array([5, 6,4])

print(f"Vector 1: {v1}")
print(f"Vector 2: {v2}")
print("-" * 30)

# 1. SUMA Y RESTA (Validación de dimensiones)
if v1.shape == v2.shape:
    suma = v1 + v2
    resta = v1 - v2
    print(f"Suma: {suma}")
    print(f"Resta: {resta}")
else:
    print("Error: La Suma y Resta requieren que ambos vectores tengan el mismo tamaño.")

# 2. PRODUCTO PUNTO
if v1.size == v2.size:
    producto_punto = np.dot(v1, v2)
    print(f"Producto Punto (Escalar): {producto_punto}")
else:
    print(f"Error: El Producto Punto requiere que ambos tengan {v1.size} elementos (v2 tiene {v2.size}).")

# 3. PRODUCTO CRUZ (Validación R3)
if v1.size == 3 and v2.size == 3:
    producto_cruz = np.cross(v1, v2)
    print(f"Producto Cruz: {producto_cruz}")
else:
    print("Error: El Producto Cruz solo es posible con vectores de exactamente 3 elementos.")

# 4. DIVISIÓN (Validación de Hadamard y Nota Matemática)
if v1.size == v2.size:
    # Usamos -1 para que sean vertical y horizontal
    v1_fila = v1.reshape(1, -1)
    v2_columna = v2.reshape(-1, 1)
    print(f"Producto Matricial (Fila x Columna):\n{v1_fila @ v2_columna}")
else:
    print("Error: No se puede transformar a Fila x Columna si los tamaños no coinciden.")

#2. Realice un programa que sume, reste, multiplique (producto punto y producto cruz) y divida dos
#matrices previamente inicializadas.

import numpy as np

# 1. Inicialización de matrices
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)
print("=" * 30)

# 2. SUMA Y RESTA
# REGLA: Deben tener exactamente las mismas dimensiones (Filas y Columnas).
if A.shape == B.shape:
    print("\n1. Suma (A + B):\n", A + B)
    print("\n2. Resta (A - B):\n", A - B)
else:
    print("\nError: Suma/Resta imposible. Las matrices deben ser del mismo tamaño.")

# 3. PRODUCTO MATRICIAL (Punto)
# REGLA: Columnas de A deben ser iguales a Filas de B.
if A.shape[1] == B.shape[0]:
    producto_matricial = A @ B
    print("\n3. Producto Matricial (A @ B):\n", producto_matricial)
else:
    print("\nError: Multiplicación imposible. Columnas de A != Filas de B.")

# 4. PRODUCTO CRUZ
if A.shape[1] == 3 and B.shape[1] == 3:
    print("\n4. Producto Cruz (Fila por fila):\n", np.cross(A, B))
else:
    print("\nError: El Producto Cruz requiere que las filas sean vectores de 3D.")

# 5. DIVISIÓN (Hadamard)

if A.shape == B.shape:
  # REGLA: No debe haber ceros en la matriz B para evitar error de división.
    if np.any(B == 0):
        print("\nError: División de Hadamard abortada. La matriz B contiene ceros.")
    else:
        division = A / B
        print("\n5. División (Hadamard):\n", np.round(division, 2))
        print("> Nota: Esta operación elemento a elemento NO es una división matricial algebraica.")
else:
    print("\nError: Dimensiones incompatibles para división de Hadamard.")

#3. Realice un programa que convierta coordenadas rectangulares a cilíndricas y esféricas, para lo cual
#deben consultar sobre el uso de funciones trigonométricas en Python.

import math

x = float(input("Ingresa la coordenada x: "))
y = float(input("Ingresa la coordenada y: "))
z = float(input("Ingresa la coordenada z: "))

print("-" * 30)

# --- CÁLCULOS PARA CILÍNDRICAS ---
rho = math.sqrt(x**2 + y**2)
phi_rad = math.atan2(y, x)
phi_deg = math.degrees(phi_rad) # Convertir a grados

# --- CÁLCULOS PARA ESFÉRICAS ---
r = math.sqrt(x**2 + y**2 + z**2)
# Usamos math.acos para la inclinación (theta)
# r debe ser > 0 para evitar división por cero
if r != 0:
    theta_rad = math.acos(z / r)
else:
    theta_rad = 0
theta_deg = math.degrees(theta_rad)

# --- MOSTRAR RESULTADOS ---
print("COORDENADAS CILÍNDRICAS:")
print(f"Radio (rho): {rho:.2f}")
print(f"Ángulo (phi): {phi_deg:.2f}°")
print(f"Altura (z): {z}")

print("-" * 30)

print("COORDENADAS ESFÉRICAS:")
print(f"Radio (r): {r:.2f}")
print(f"Inclinación (theta): {theta_deg:.2f}°")
print(f"Azimut (phi): {phi_deg:.2f}°")
print("-" * 30)

#4. Realice un programa para el cálculo de la resistencia de una RTD de platino (PT100) en función de
#la temperatura.

import math

def calcular_resistencia_pt100(t):
    # coeficientes de Callendar-Van Dusen
    R0 = 100.0
    A = 3.9083e-3
    B = -5.775e-7
    C = -4.183e-12

    if t >= 0:
        rt = R0 * (1 + A * t + B * t**2)
    else:
        rt = R0 * (1 + A * t + B * t**2 + C * (t - 100) * t**3)
    return rt

# Interacción con el usuario
print("-" * 30)
try:
    temp = float(input("Ingresa la temperatura en °C: "))
    resistencia = calcular_resistencia_pt100(temp)

    print("-" * 30)
    print(f"RESULTADO PARA {temp}°C")
    print(f"Resistencia estimada: {resistencia:.4f} Ω")
    print("-" * 30)

except ValueError:
    print("Error: Por favor ingresa un número válido.")

#5. Realice en funciones las rotaciones en X, Y y Z, donde se tenga un parámetro de entrada (ángulo)
#y un parámetro de salida (matriz).

import math

def rotacion_x(angulo_grados):
    # Convertimos a radianes porque math.sin/cos
    rad = math.radians(angulo_grados)
    c, s = math.cos(rad), math.sin(rad)

    # Construimos la matriz como una lista de listas
    matriz = [
        [1, 0,  0],
        [0, c, -s],
        [0, s,  c]
    ]
    return matriz

def rotacion_y(angulo_grados):
    rad = math.radians(angulo_grados)
    c, s = math.cos(rad), math.sin(rad)

    matriz = [
        [ c, 0, s],
        [ 0, 1, 0],
        [-s, 0, c]
    ]
    return matriz

def rotacion_z(angulo_grados):
    rad = math.radians(angulo_grados)
    c, s = math.cos(rad), math.sin(rad)

    matriz = [
        [c, -s, 0],
        [s,  c, 0],
        [0,  0, 1]
    ]
    return matriz

# --- Ejemplo de uso para probar el programa ---
angulo = 45
m_z = rotacion_z(angulo)

print(f"Matriz de Rotación en Z para {angulo}°:")
print("-" * 40)
for fila in m_z:
    print(fila)
print("-" * 40)

#6. Realice un programa que calcule la fuerza de avance y retroceso de un cilindro neumático de doble
#efecto. Debe establecer previamente los valores de presión, así como las dimensiones físicas del
#cilindro para realizar el cálculo

import math

# 1. Entrada de datos
d_embolo_mm = float(input("Diámetro del émbolo (en mm): "))
d_vastago_mm = float(input("Diámetro del vástago (en mm): "))

# --- EL LIMITANTE ---
if d_vastago_mm >= d_embolo_mm:
    print("-" * 40)
    print("❌ ERROR DE DISEÑO: El vástago debe ser menor que el émbolo.")
    print("-" * 40)
else:
    presion_bar = float(input("Presión de trabajo (en Bares): "))

    # 2. CONVERSIÓN DE UNIDADES
    d_embolo_m = d_embolo_mm / 1000
    d_vastago_m = d_vastago_mm / 1000
    presion_pa = presion_bar * 100000

    # 3. CÁLCULO DE ÁREAS (m²)
    area_avance = (math.pi * d_embolo_m**2) / 4

    # Área de retroceso (cara del émbolo menos la sección del vástago)
    area_anular = (math.pi * (d_embolo_m**2 - d_vastago_m**2)) / 4

    # 4. CÁLCULO DE FUERZAS (Newtons)
    fuerza_avance = presion_pa * area_avance
    fuerza_retroceso = presion_pa * area_anular

    # 5. MOSTRAR RESULTADOS
    print("\n" + "=" * 40)
    print("✅ CÁLCULO REALIZADO CON ÉXITO")
    print("-" * 40)
    print(f"Fuerza de Avance: {fuerza_avance:.2f} N")
    print(f"Fuerza de Retroceso: {fuerza_retroceso:.2f} N")
    print("=" * 40)