# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLS0FrwqxbH2l0bR7zAk1GF9sdSnkv9I
"""

#Realice un programa que grafique el comportamiento de un sensor PT100 desde -200°C a 200°C.

import matplotlib.pyplot as plt

R0 = 100
A = 3.9083e-3
B = -5.775e-7
C = -4.183e-12

T = []
R = []

for i in range(-200, 200, 1):
    Ti = i
    if Ti >= 0:
        Ri = R0 * (1 + A*Ti + B*(Ti**2))
    else:
        Ri = R0 * (1 + A*Ti + B*(Ti**2) + C*(Ti - 100)*(Ti**3))

    T.append(Ti)
    R.append(Ri)

# Graficar
plt.plot(T, R)
plt.xlabel("Temperatura (°C)")
plt.ylabel("Resistencia (Ω)")
plt.title("Sensor PT100 ")
plt.grid(True)
plt.show()

#2. Realice un programa que le permita al usuario ingresar los coeficientes de una función de
#transferencia de segundo orden y graficar su comportamiento, además se debe mostrar que tipo
#de sistema es: subamortiguado, criticamente amortiguado y sobreamortiguado.

import numpy as np
import matplotlib.pyplot as plt

K = float(input("Ingrese la ganancia K: "))
factor_amortiguamiento = float(input("Ingrese el factor de amortiguamiento (ζ): "))
frecuencia_natural = float(input("Ingrese la frecuencia natural (ωn) en rad/s: "))

# Validaciones (tau todavía no existe, así que se valida lo que sí ingresaste)
if factor_amortiguamiento <= 0 or frecuencia_natural <= 0:
    raise ValueError("El factor de amortiguamiento y la frecuencia natural deben ser positivos.")

# Relación usada en tu código
tau = 1.0 / (factor_amortiguamiento * frecuencia_natural)

# Clasificación
eps = 1e-9
if factor_amortiguamiento < 1 - eps:
    tipo = "Subamortiguado"
elif abs(factor_amortiguamiento - 1) <= 1e-6:
    tipo = "Criticamente amortiguado"
else:
    tipo = "Sobreamortiguado"

print("\nResultados")
print("Factor de amortiguamiento =", factor_amortiguamiento)
print("tau =", tau)
print("Tipo =", tipo)

# Tiempo de simulación
t_end = max(10 * tau, 1.0)
t = np.linspace(0, t_end, 2000)

# Respuesta al escalón unitario y(t)
if factor_amortiguamiento < 1 - eps:
    frecuencia_amortiguada = frecuencia_natural * np.sqrt(1 - factor_amortiguamiento**2)
    y = K * (1 - np.exp(-factor_amortiguamiento * frecuencia_natural * t) * (
        np.cos(frecuencia_amortiguada * t) +
        (factor_amortiguamiento / np.sqrt(1 - factor_amortiguamiento**2)) *
        np.sin(frecuencia_amortiguada * t)
    ))

elif abs(factor_amortiguamiento - 1) <= 1e-6:
    y = K * (1 - np.exp(-frecuencia_natural * t) * (1 + frecuencia_natural * t))

else:
    a = np.sqrt(factor_amortiguamiento**2 - 1)
    y = K * (1 - (1/(2*a)) * (
        (factor_amortiguamiento + a) * np.exp(-(factor_amortiguamiento - a) * frecuencia_natural * t) -
        (factor_amortiguamiento - a) * np.exp(-(factor_amortiguamiento + a) * frecuencia_natural * t)
    ))

plt.plot(t, y)
plt.xlabel("Tiempo (s)")
plt.ylabel("Salida y(t)")
plt.title(
    f"Respuesta al escalon (K={K}, tau={tau:.4f}, ωn={frecuencia_natural})\n"
    f"{tipo} (ζ={factor_amortiguamiento:.4f})"
)
plt.grid(True)
plt.show()

#3. Implemente la ecuación de carga y descarga para un circuito RC. El usuario ingresa por teclado el
#valor de voltaje (V), capacitancia (𝜇𝐹) y resistencia (Ω).  Posteriormente realice en Python la
#gráfica.


import numpy as np
import matplotlib.pyplot as plt

# Entrada por teclado
R = float(input("Ingrese la resistencia R (Ohmios): "))
C_micro = float(input("Ingrese la capacitancia C (microfaradios µF): "))
V = float(input("Ingrese el voltaje de la fuente V (Voltios): "))

if R <= 0 or C_micro <= 0:
    raise ValueError("R y C deben ser positivos.")


C = C_micro * 1e-6


tau = R * C
print("Constante de tiempo τ =", tau, "segundos")


t = np.linspace(0, 5*tau, 1000)

# Ecuación de carga
Vc = V * (1 - np.exp(-t / tau))


plt.plot(t, Vc)
plt.xlabel("Tiempo (s)")
plt.ylabel("Voltaje del capacitor Vc(t)")
plt.title("Carga de un circuito RC")
plt.grid(True)
plt.show()

#4. Consulte y elabore un sistema coordenado X, Y y Z donde se dibuje un vector con coordenadas
#ingresadas por el usuario.

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


print("Introduce las componentes del vector:")
x = float(input("Componente X: "))
y = float(input("Componente Y: "))
z = float(input("Componente Z: "))


fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')


ax.quiver(0, 0, 0, x, y, z, color='blue', arrow_length_ratio=0.1)


limite = max(abs(x), abs(y), abs(z), 1)
ax.set_xlim([0, limite])
ax.set_ylim([0, limite])
ax.set_zlim([0, limite])

ax.set_xlabel('Eje X')
ax.set_ylabel('Eje Y')
ax.set_zlabel('Eje Z')
ax.set_title(f'Vector 3D: ({x}, {y}, {z})')

plt.show()

#5. Dibuje el nombre de cada uno de los integrantes del grupo en un plot en 2D, teniendo en cuenta
#líneas rectas y/o curvas.

import matplotlib.pyplot as plt

alfabeto = {
    'A': [(0, 0), (0.5, 2), (1, 0), None, (0.2, 0.8), (0.8, 0.8)],
    'B': [(0, 0), (0, 2), (0.7, 2), (1, 1.5), (0.7, 1), (0, 1), None, (0.7, 1), (1, 0.5), (0.7, 0), (0, 0)],
    'C': [(1, 0.2), (0.8, 0), (0.2, 0), (0, 0.2), (0, 1.8), (0.2, 2), (0.8, 2), (1, 1.8)],
    'D': [(0, 0), (0, 2), (0.6, 2), (1, 1.5), (1, 0.5), (0.6, 0), (0, 0)],
    'E': [(1, 0), (0, 0), (0, 2), (1, 2), None, (0, 1), (0.7, 1)],
    'F': [(0, 0), (0, 2), (1, 2), None, (0, 1), (0.7, 1)],
    'G': [(1, 1.5), (1, 2), (0.2, 2), (0, 1.8), (0, 0.2), (0.2, 0), (0.8, 0), (1, 0.2), (1, 1), (0.5, 1)],
    'H': [(0, 0), (0, 2), None, (1, 0), (1, 2), None, (0, 1), (1, 1)],
    'I': [(0.2, 2), (0.8, 2), None, (0.5, 2), (0.5, 0), None, (0.2, 0), (0.8, 0)],
    'J': [(0, 0.5), (0.2, 0), (0.8, 0), (1, 0.2), (1, 2)],
    'K': [(0, 0), (0, 2), None, (1, 2), (0, 1), (1, 0)],
    'L': [(0, 2), (0, 0), (1, 0)],
    'M': [(0, 0), (0, 2), (0.5, 1), (1, 2), (1, 0)],
    'N': [(0, 0), (0, 2), (1, 0), (1, 2)],
    'O': [(0.2, 0), (0.8, 0), (1, 0.2), (1, 1.8), (0.8, 2), (0.2, 2), (0, 1.8), (0, 0.2), (0.2, 0)],
    'P': [(0, 0), (0, 2), (0.8, 2), (1, 1.5), (0.8, 1), (0, 1)],
    'Q': [(0.2, 0), (0.8, 0), (1, 0.2), (1, 1.8), (0.8, 2), (0.2, 2), (0, 1.8), (0, 0.2), (0.2, 0), None, (0.6, 0.6), (1, 0)],
    'R': [(0, 0), (0, 2), (0.8, 2), (1, 1.5), (0.8, 1), (0, 1), None, (0.6, 1), (1, 0)],
    'S': [(0, 0.2), (0.2, 0), (0.8, 0), (1, 0.2), (1, 0.8), (0, 1.2), (0, 1.8), (0.2, 2), (0.8, 2), (1, 1.8)],
    'T': [(0.5, 0), (0.5, 2), None, (0, 2), (1, 2)],
    'U': [(0, 2), (0, 0.2), (0.2, 0), (0.8, 0), (1, 0.2), (1, 2)],
    'V': [(0, 2), (0.5, 0), (1, 2)],
    'W': [(0, 2), (0.2, 0), (0.5, 1), (0.8, 0), (1, 2)],
    'X': [(0, 0), (1, 2), None, (0, 2), (1, 0)],
    'Y': [(0, 2), (0.5, 1), (1, 2), None, (0.5, 1), (0.5, 0)],
    'Z': [(0, 2), (1, 2), (0, 0), (1, 0)],
    ' ': []
}

nombre = input("Ingresa tu nombre completo: ").upper()

fig, ax = plt.subplots(figsize=(len(nombre)*1.5, 4))
cursor_x = 0

for caracter in nombre:
    if caracter in alfabeto:
        puntos = alfabeto[caracter]
        x_coords, y_coords = [], []

        for p in puntos:
            if p is None:
                ax.plot(x_coords, y_coords, color='darkblue', linewidth=3)
                x_coords, y_coords = [], []
            else:
                x_coords.append(p[0] + cursor_x)
                y_coords.append(p[1])

        ax.plot(x_coords, y_coords, color='darkblue', linewidth=3)

    cursor_x += 1.5 # Espacio entre letras

# Configuración final
ax.set_aspect('equal')
ax.grid(True, linestyle=':', alpha=0.5)
ax.set_title(f"Dibujo de: {nombre}")
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
import os

# --- PASO 0: Entrada por consola ---
ruta_imagen = input("Introduce el nombre o ruta de la imagen del logo (ej. chevrolet.png): ")

# Verificamos si el archivo existe antes de seguir
if not os.path.exists(ruta_imagen):
    print(f"Error: No se encuentra el archivo '{ruta_imagen}'.")
else:
    # 1. Carga de la imagen
    imagen = cv2.imread(ruta_imagen)

    # 2. Conversión a Escala de Grises
    gris = cv2.cvtColor(imagen, cv2.COLOR_BGR2GRAY)

    # 3. Suavizado (Filtro para limpiar impurezas)
    suave = cv2.GaussianBlur(gris, (5, 5), 0)

    # 4. Binarización (Umbralización)
    # Usamos cv2.THRESH_OTSU para que Python calcule el mejor umbral automáticamente
    _, binaria = cv2.threshold(suave, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

   # ... (Pasos previos: carga, gris, binarización) ...

# 5. Detección de Contornos (buscamos todos, no solo el externo)
contornos, _ = cv2.findContours(binaria, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)

plt.figure(figsize=(10, 4))

# 6, 7 y 8. Procesar cada trazo detectado
for cnt in contornos:
    # Filtro opcional: omitir puntos muy pequeños (ruido)
    if cv2.contourArea(cnt) > 5:
        puntos = cnt.reshape(-1, 2)
        x = puntos[:, 0]
        y = puntos[:, 1]

        # Inversión del Eje Y
        y_cartesiano = alto_imagen - y

        # Graficamos cada trazo por separado
        plt.plot(x, y_cartesiano, color='blue', linewidth=1.5)

plt.gca().set_aspect('equal')
plt.title("Firma Completa en el Plano Cartesiano")
plt.grid(True, linestyle=':', alpha=0.5)
plt.show()
for xi, yi in zip(x, y_cartesiano):
    print(f"[{xi}, {yi}]")
